behagerlij/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tables/', include('tables.urls')),
    path('', include('myprofile.urls')),
]

myprofile/urls.py
from django.urls import path

from . import views

app_name = 'myprofile'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='table-list'),
    path('table/add/', views.ProfileFamilyMemberCreate.as_view(), name='table-add'),
    path('table/<int:pk>', views.ProfileFamilyMemberUpdate.as_view(), name='table-update'),
    path('table/delete/<int:pk>', views.ProfileDelete.as_view(), name='table-delete'),
]

tables/urls.py
from django.urls import path
from .import  views
app_name = 'tables'
urlpatterns=[
     path('create-work/',views.create_work.as_view(), name='create_work'),
     path('table/<int:pk>', views.ProfileFamilyMemberUpdate.as_view(), name='table-update'),
     path('', views.ProfileList.as_view(), name='table-list'),
   
]

myprofile/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Table(models.Model):
    table_name = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('myprofile:profile-update', kwargs={'pk': self.pk})

    def __str__(self):
        return self.table_name



class Feilds(models.Model):
    tables = models.ForeignKey(Table, on_delete = models.CASCADE)
    field_name = models.CharField(max_length=20)
    field_data_type = models.CharField(max_length=20)
    field_max_length = models.CharField(max_length=20)

    def __str__(self):
        return self.field_name

tables/models.py
from django.db import models
from django.urls import reverse

# from django.contrib.auth.models import AbstractUser

class Table(models.Model):
    table_name = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('table-update', kwargs={'pk': self.pk})

    def __str__(self):
        return self.table_name

class Feilds(models.Model):
    tables = models.ForeignKey(Table, on_delete = models.CASCADE)
    field_name = models.CharField(max_length=20)
    field_data_type = models.CharField(max_length=20)
    field_max_length = models.CharField(max_length=20)
    
    def __str__(self):
        return self.field_name

myprofile/forms.py
from django.forms import ModelForm, inlineformset_factory

from .models import Table,Feilds


class ProfileForm(ModelForm):
    class Meta:
        model = Table
        exclude = ()


class FamilyMemberForm(ModelForm):
    class Meta:
        model = Feilds
        exclude = ()


FamilyMemberFormSet = inlineformset_factory(Table, Feilds,
                                            form=FamilyMemberForm, extra=1)

tables/forms.py
from dataclasses import Field
from django import forms
from django.forms import ModelChoiceField, inlineformset_factory
from .models import Table,Feilds



class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        exclude = ()

data_types =(
    ("string", "string"),
    ("nubmer", "number"),
)
class FeildsForm(forms.ModelForm):
    # field_data_type=forms.ChoiceField(choices = data_types)
    # field_max_length = forms.IntegerField()
    class Meta:
        model = Feilds
        exclude = ()



FeildsInlineFormset = inlineformset_factory(Table, Feilds,
                                            form=FeildsForm, extra=1)
  

myprofile/views.py
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import FamilyMemberFormSet
from .models import Table


class ProfileList(ListView):
    model = Table


class ProfileCreate(CreateView):
    model = Table
    fields = ['table_name']

class ProfileFamilyMemberCreate(CreateView):
    model = Table
    fields = ['table_name']
    success_url = reverse_lazy('myprofile:table-list')

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['feilds'] = FamilyMemberFormSet(self.request.POST)
        else:
            data['feilds'] = FamilyMemberFormSet()
        return data
        
    # Animal = type("Animal", (models.Model,), attrs)
    # with connection.schema_editor() as schema_editor:
    #     schema_editor.create_model(Animal)
    def form_valid(self, form):
        context = self.get_context_data()
        feilds = context['feilds']
        with transaction.atomic():
            # self.object = form.save()

            if feilds.is_valid():
                feilds.instance = self.object
                # feilds.save()
                attrs = {}
# for j in xrange(10):
#     key_j = 'key_{}'.format(j)  # a string depending on j
#     res[key_j] = j**2
                for i in feilds.cleaned_data:
                    field_name = '{}'.format(i['field_name'])
                    field_data_type = '{}'.format(i['field_data_type'])
                    field_max_length = '{}'.format(i['field_max_length'])
                    attrs[field_name] = 'models.'+field_data_type+'(max_length='+field_max_length+'),'
                    # print(key)

           
                # attrs['__module__']='accounts.models'
                print(attrs)
        return super(ProfileFamilyMemberCreate, self).form_valid(form)


class ProfileUpdate(UpdateView):
    model = Table
    success_url = '/'
    fields = ['table_name']


class ProfileFamilyMemberUpdate(UpdateView):
    model = Table
    fields = ['table_name']
    success_url = reverse_lazy('myprofile:table-list')

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['feilds'] = FamilyMemberFormSet(self.request.POST, instance=self.object)
        else:
            data['feilds'] = FamilyMemberFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        feilds = context['feilds']
        with transaction.atomic():
            self.object = form.save()

            if feilds.is_valid():
                feilds.instance = self.object
                feilds.save()
        return super(ProfileFamilyMemberUpdate, self).form_valid(form)


class ProfileDelete(DeleteView):
    model = Table
    success_url = reverse_lazy('myprofile:table-list')

tables/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, ListView, CreateView
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.urls import reverse
from django.db import transaction
from django.urls import reverse_lazy

# Create your views here.
# def create_work(request):
#     return render(request,'account/worktype.html',)

class ProfileList(ListView):
    model = Table

class create_work(CreateView):
    model = Table
    fields = ['table_name']
    success_url = reverse_lazy('tables:create_work')
    # form_class = FeildsInlineFormset()

    def get_context_data(self, **kwargs):
        data = super(create_work, self).get_context_data(**kwargs)
        if self.request.POST:
            data['familymembers'] = FeildsInlineFormset(self.request.POST)
            attrs = {
                self.request.POST['table_name']: models.CharField(max_length=32),
                '__module__': 'accounts.models'
                }
            
                    # Animal = type("Animal", (models.Model,), attrs)
                    # with connection.schema_editor() as schema_editor:
                    #     schema_editor.create_model(Animal)
            
        else:
            data['familymembers'] = FeildsInlineFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        # for f in context['familymembers']: 
        #     # cd = f.cleaned_data
        #     # first_name = cd.get('first_name')
        #     print(f)
        print()
        familymembers = context['familymembers']
        with transaction.atomic():
            self.object = form.save()

            if familymembers.is_valid():
                familymembers.instance = self.object
                familymembers.save()
        return super(create_work, self).form_valid(form)

class ProfileFamilyMemberUpdate(UpdateView):
    model = Table
    fields = ['table_name']
    success_url = reverse_lazy('table-list')

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['familymembers'] = FeildsInlineFormset(self.request.POST, instance=self.object)
        else:
            data['familymembers'] = FeildsInlineFormset(instance=self.object)
        return data

templates/myprofile/table_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block content %}
    <h2></h2>
    <hr>
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

templates/myprofile/table_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock %}
{% block content %}
    <h2>Profile</h2>
    <hr>
    <div class="col-md-4">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}

            <table class="table">
                {{ feilds.management_form }}

                {% for form in feilds.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" value="Save"/> <a href="{% url 'myprofile:table-list' %}">back to the list</a>
        </form>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'add field',
            deleteText: 'remove',
            prefix: 'feilds_set'
        });
    </script>
{% endblock %}

templates/myprofile/table_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}

    <h2>Here are all user profiles: </h2>
    <div>
        <ul>
            {% for profile in object_list %}
                <li>{{ profile.table_name }}| <a
                        href="{% url 'myprofile:table-update' profile.pk %}">edit</a>
                    <a href="{% url 'myprofile:table-delete' profile.pk %}">delete</a>
                </li>
            {% empty %}
                <li>No profile yet.</li>
            {% endfor %}

        </ul>
        <p>
            <a href="{% url 'myprofile:table-add' %}">add a profile</a>
        </p>
    </div>
{% endblock %}